python ./poseLandmark_test.py -i 0.jpg >> log.txt
python ./poseLandmark_test.py -i 1.jpg >> log.txt
python ./poseLandmark_test.py -i 2.jpg >> log.txt
python ./poseLandmark_test.py -i 3.jpg >> log.txt
python ./poseLandmark_test.py -i 4.jpg >> log.txt
python ./poseLandmark_test.py -i 5.jpg >> log.txt
python ./poseLandmark_test.py -i 6.jpg >> log.txt
python ./poseLandmark_test.py -i 7.jpg >> log.txt
python ./poseLandmark_test.py -i 8.jpg >> log.txt
python ./poseLandmark_test.py -i 9.jpg >> log.txt
python ./poseLandmark_test.py -i 10.jpg >> log.txt
python ./poseLandmark_test.py -i 11.jpg >> log.txt
python ./poseLandmark_test.py -i 12.jpg >> log.txt
python ./poseLandmark_test.py -i 13.jpg >> log.txt
python ./poseLandmark_test.py -i 14.jpg >> log.txt
python ./poseLandmark_test.py -i 15.jpg >> log.txt
python ./poseLandmark_test.py -i 16.jpg >> log.txt
python ./poseLandmark_test.py -i 17.jpg >> log.txt
python ./poseLandmark_test.py -i 18.jpg >> log.txt
python ./poseLandmark_test.py -i 19.jpg >> log.txt
python ./poseLandmark_test.py -i 20.jpg >> log.txt
python ./poseLandmark_test.py -i 21.jpg >> log.txt
python ./poseLandmark_test.py -i 22.jpg >> log.txt
python ./poseLandmark_test.py -i 23.jpg >> log.txt
python ./poseLandmark_test.py -i 24.jpg >> log.txt
python ./poseLandmark_test.py -i 25.jpg >> log.txt
python ./poseLandmark_test.py -i 26.jpg >> log.txt
python ./poseLandmark_test.py -i 27.jpg >> log.txt
python ./poseLandmark_test.py -i 28.jpg >> log.txt
python ./poseLandmark_test.py -i 29.jpg >> log.txt
python ./poseLandmark_test.py -i 30.jpg >> log.txt
python ./poseLandmark_test.py -i 31.jpg >> log.txt
python ./poseLandmark_test.py -i 32.jpg >> log.txt
python ./poseLandmark_test.py -i 33.jpg >> log.txt
python ./poseLandmark_test.py -i 34.jpg >> log.txt
python ./poseLandmark_test.py -i 35.jpg >> log.txt
python ./poseLandmark_test.py -i 36.jpg >> log.txt
python ./poseLandmark_test.py -i 37.jpg >> log.txt
python ./poseLandmark_test.py -i 38.jpg >> log.txt
python ./poseLandmark_test.py -i 39.jpg >> log.txt
python ./poseLandmark_test.py -i 40.jpg >> log.txt
python ./poseLandmark_test.py -i 41.jpg >> log.txt
python ./poseLandmark_test.py -i 42.jpg >> log.txt
python ./poseLandmark_test.py -i 43.jpg >> log.txt
python ./poseLandmark_test.py -i 44.jpg >> log.txt
python ./poseLandmark_test.py -i 45.jpg >> log.txt
python ./poseLandmark_test.py -i 46.jpg >> log.txt
python ./poseLandmark_test.py -i 47.jpg >> log.txt
python ./poseLandmark_test.py -i 48.jpg >> log.txt
python ./poseLandmark_test.py -i 49.jpg >> log.txt
python ./poseLandmark_test.py -i 50.jpg >> log.txt
python ./poseLandmark_test.py -i 51.jpg >> log.txt
python ./poseLandmark_test.py -i 52.jpg >> log.txt
python ./poseLandmark_test.py -i 53.jpg >> log.txt
python ./poseLandmark_test.py -i 54.jpg >> log.txt
python ./poseLandmark_test.py -i 55.jpg >> log.txt
python ./poseLandmark_test.py -i 56.jpg >> log.txt
python ./poseLandmark_test.py -i 57.jpg >> log.txt
python ./poseLandmark_test.py -i 58.jpg >> log.txt
python ./poseLandmark_test.py -i 59.jpg >> log.txt
python ./poseLandmark_test.py -i 60.jpg >> log.txt
python ./poseLandmark_test.py -i 61.jpg >> log.txt
python ./poseLandmark_test.py -i 62.jpg >> log.txt
python ./poseLandmark_test.py -i 63.jpg >> log.txt
python ./poseLandmark_test.py -i 64.jpg >> log.txt
python ./poseLandmark_test.py -i 65.jpg >> log.txt
python ./poseLandmark_test.py -i 66.jpg >> log.txt
python ./poseLandmark_test.py -i 67.jpg >> log.txt
python ./poseLandmark_test.py -i 68.jpg >> log.txt
python ./poseLandmark_test.py -i 69.jpg >> log.txt
python ./poseLandmark_test.py -i 70.jpg >> log.txt
python ./poseLandmark_test.py -i 71.jpg >> log.txt
python ./poseLandmark_test.py -i 72.jpg >> log.txt
python ./poseLandmark_test.py -i 73.jpg >> log.txt
python ./poseLandmark_test.py -i 74.jpg >> log.txt
python ./poseLandmark_test.py -i 75.jpg >> log.txt
python ./poseLandmark_test.py -i 76.jpg >> log.txt
python ./poseLandmark_test.py -i 77.jpg >> log.txt
python ./poseLandmark_test.py -i 78.jpg >> log.txt
python ./poseLandmark_test.py -i 79.jpg >> log.txt
python ./poseLandmark_test.py -i 80.jpg >> log.txt
python ./poseLandmark_test.py -i 81.jpg >> log.txt
python ./poseLandmark_test.py -i 82.jpg >> log.txt
python ./poseLandmark_test.py -i 83.jpg >> log.txt
python ./poseLandmark_test.py -i 84.jpg >> log.txt
python ./poseLandmark_test.py -i 85.jpg >> log.txt
python ./poseLandmark_test.py -i 86.jpg >> log.txt
python ./poseLandmark_test.py -i 87.jpg >> log.txt
python ./poseLandmark_test.py -i 88.jpg >> log.txt
python ./poseLandmark_test.py -i 89.jpg >> log.txt
python ./poseLandmark_test.py -i 90.jpg >> log.txt
python ./poseLandmark_test.py -i 91.jpg >> log.txt
python ./poseLandmark_test.py -i 92.jpg >> log.txt
python ./poseLandmark_test.py -i 93.jpg >> log.txt
python ./poseLandmark_test.py -i 94.jpg >> log.txt
python ./poseLandmark_test.py -i 95.jpg >> log.txt
python ./poseLandmark_test.py -i 96.jpg >> log.txt
python ./poseLandmark_test.py -i 97.jpg >> log.txt
python ./poseLandmark_test.py -i 98.jpg >> log.txt
python ./poseLandmark_test.py -i 99.jpg >> log.txt
python ./poseLandmark_test.py -i 100.jpg >> log.txt
python ./poseLandmark_test.py -i 101.jpg >> log.txt
python ./poseLandmark_test.py -i 102.jpg >> log.txt
python ./poseLandmark_test.py -i 103.jpg >> log.txt
python ./poseLandmark_test.py -i 104.jpg >> log.txt
python ./poseLandmark_test.py -i 105.jpg >> log.txt
python ./poseLandmark_test.py -i 106.jpg >> log.txt
python ./poseLandmark_test.py -i 107.jpg >> log.txt
python ./poseLandmark_test.py -i 108.jpg >> log.txt
python ./poseLandmark_test.py -i 109.jpg >> log.txt
python ./poseLandmark_test.py -i 110.jpg >> log.txt
python ./poseLandmark_test.py -i 111.jpg >> log.txt
python ./poseLandmark_test.py -i 112.jpg >> log.txt
python ./poseLandmark_test.py -i 113.jpg >> log.txt
python ./poseLandmark_test.py -i 114.jpg >> log.txt
python ./poseLandmark_test.py -i 115.jpg >> log.txt
python ./poseLandmark_test.py -i 116.jpg >> log.txt
python ./poseLandmark_test.py -i 117.jpg >> log.txt
python ./poseLandmark_test.py -i 118.jpg >> log.txt
python ./poseLandmark_test.py -i 119.jpg >> log.txt
python ./poseLandmark_test.py -i 120.jpg >> log.txt
python ./poseLandmark_test.py -i 121.jpg >> log.txt
python ./poseLandmark_test.py -i 122.jpg >> log.txt
python ./poseLandmark_test.py -i 123.jpg >> log.txt
python ./poseLandmark_test.py -i 124.jpg >> log.txt
python ./poseLandmark_test.py -i 125.jpg >> log.txt
python ./poseLandmark_test.py -i 126.jpg >> log.txt
python ./poseLandmark_test.py -i 127.jpg >> log.txt
python ./poseLandmark_test.py -i 128.jpg >> log.txt
python ./poseLandmark_test.py -i 129.jpg >> log.txt
python ./poseLandmark_test.py -i 130.jpg >> log.txt
python ./poseLandmark_test.py -i 131.jpg >> log.txt
python ./poseLandmark_test.py -i 132.jpg >> log.txt
python ./poseLandmark_test.py -i 133.jpg >> log.txt
python ./poseLandmark_test.py -i 134.jpg >> log.txt
python ./poseLandmark_test.py -i 135.jpg >> log.txt
python ./poseLandmark_test.py -i 136.jpg >> log.txt
python ./poseLandmark_test.py -i 137.jpg >> log.txt
python ./poseLandmark_test.py -i 138.jpg >> log.txt
python ./poseLandmark_test.py -i 139.jpg >> log.txt
python ./poseLandmark_test.py -i 140.jpg >> log.txt
python ./poseLandmark_test.py -i 141.jpg >> log.txt
python ./poseLandmark_test.py -i 142.jpg >> log.txt
python ./poseLandmark_test.py -i 143.jpg >> log.txt
python ./poseLandmark_test.py -i 144.jpg >> log.txt
python ./poseLandmark_test.py -i 145.jpg >> log.txt
python ./poseLandmark_test.py -i 146.jpg >> log.txt
python ./poseLandmark_test.py -i 147.jpg >> log.txt
python ./poseLandmark_test.py -i 148.jpg >> log.txt
python ./poseLandmark_test.py -i 149.jpg >> log.txt
python ./poseLandmark_test.py -i 150.jpg >> log.txt
python ./poseLandmark_test.py -i 151.jpg >> log.txt
python ./poseLandmark_test.py -i 152.jpg >> log.txt
python ./poseLandmark_test.py -i 153.jpg >> log.txt
python ./poseLandmark_test.py -i 154.jpg >> log.txt
python ./poseLandmark_test.py -i 155.jpg >> log.txt
python ./poseLandmark_test.py -i 156.jpg >> log.txt
python ./poseLandmark_test.py -i 157.jpg >> log.txt
python ./poseLandmark_test.py -i 158.jpg >> log.txt
python ./poseLandmark_test.py -i 159.jpg >> log.txt
python ./poseLandmark_test.py -i 160.jpg >> log.txt
python ./poseLandmark_test.py -i 161.jpg >> log.txt
python ./poseLandmark_test.py -i 162.jpg >> log.txt
python ./poseLandmark_test.py -i 163.jpg >> log.txt
python ./poseLandmark_test.py -i 164.jpg >> log.txt
python ./poseLandmark_test.py -i 165.jpg >> log.txt
python ./poseLandmark_test.py -i 166.jpg >> log.txt
python ./poseLandmark_test.py -i 167.jpg >> log.txt
python ./poseLandmark_test.py -i 168.jpg >> log.txt
python ./poseLandmark_test.py -i 169.jpg >> log.txt
python ./poseLandmark_test.py -i 170.jpg >> log.txt
python ./poseLandmark_test.py -i 171.jpg >> log.txt
python ./poseLandmark_test.py -i 172.jpg >> log.txt
python ./poseLandmark_test.py -i 173.jpg >> log.txt
python ./poseLandmark_test.py -i 174.jpg >> log.txt
python ./poseLandmark_test.py -i 175.jpg >> log.txt
python ./poseLandmark_test.py -i 176.jpg >> log.txt
python ./poseLandmark_test.py -i 177.jpg >> log.txt
python ./poseLandmark_test.py -i 178.jpg >> log.txt
python ./poseLandmark_test.py -i 179.jpg >> log.txt
python ./poseLandmark_test.py -i 180.jpg >> log.txt
python ./poseLandmark_test.py -i 181.jpg >> log.txt
python ./poseLandmark_test.py -i 182.jpg >> log.txt
python ./poseLandmark_test.py -i 183.jpg >> log.txt
python ./poseLandmark_test.py -i 184.jpg >> log.txt
python ./poseLandmark_test.py -i 185.jpg >> log.txt
python ./poseLandmark_test.py -i 186.jpg >> log.txt
python ./poseLandmark_test.py -i 187.jpg >> log.txt
python ./poseLandmark_test.py -i 188.jpg >> log.txt
python ./poseLandmark_test.py -i 189.jpg >> log.txt
python ./poseLandmark_test.py -i 190.jpg >> log.txt
python ./poseLandmark_test.py -i 191.jpg >> log.txt
python ./poseLandmark_test.py -i 192.jpg >> log.txt
python ./poseLandmark_test.py -i 193.jpg >> log.txt
python ./poseLandmark_test.py -i 194.jpg >> log.txt
python ./poseLandmark_test.py -i 195.jpg >> log.txt
python ./poseLandmark_test.py -i 196.jpg >> log.txt
python ./poseLandmark_test.py -i 197.jpg >> log.txt
python ./poseLandmark_test.py -i 198.jpg >> log.txt
python ./poseLandmark_test.py -i 199.jpg >> log.txt
python ./poseLandmark_test.py -i 200.jpg >> log.txt
python ./poseLandmark_test.py -i 201.jpg >> log.txt
python ./poseLandmark_test.py -i 202.jpg >> log.txt
python ./poseLandmark_test.py -i 203.jpg >> log.txt
python ./poseLandmark_test.py -i 204.jpg >> log.txt
python ./poseLandmark_test.py -i 205.jpg >> log.txt
python ./poseLandmark_test.py -i 206.jpg >> log.txt
python ./poseLandmark_test.py -i 207.jpg >> log.txt
python ./poseLandmark_test.py -i 208.jpg >> log.txt
python ./poseLandmark_test.py -i 209.jpg >> log.txt
python ./poseLandmark_test.py -i 210.jpg >> log.txt
python ./poseLandmark_test.py -i 211.jpg >> log.txt
python ./poseLandmark_test.py -i 212.jpg >> log.txt
python ./poseLandmark_test.py -i 213.jpg >> log.txt
python ./poseLandmark_test.py -i 214.jpg >> log.txt
python ./poseLandmark_test.py -i 215.jpg >> log.txt
python ./poseLandmark_test.py -i 216.jpg >> log.txt
python ./poseLandmark_test.py -i 217.jpg >> log.txt
python ./poseLandmark_test.py -i 218.jpg >> log.txt
python ./poseLandmark_test.py -i 219.jpg >> log.txt
python ./poseLandmark_test.py -i 220.jpg >> log.txt
python ./poseLandmark_test.py -i 221.jpg >> log.txt
python ./poseLandmark_test.py -i 222.jpg >> log.txt
python ./poseLandmark_test.py -i 223.jpg >> log.txt
python ./poseLandmark_test.py -i 224.jpg >> log.txt
python ./poseLandmark_test.py -i 225.jpg >> log.txt
python ./poseLandmark_test.py -i 226.jpg >> log.txt
python ./poseLandmark_test.py -i 227.jpg >> log.txt
python ./poseLandmark_test.py -i 228.jpg >> log.txt
python ./poseLandmark_test.py -i 229.jpg >> log.txt
python ./poseLandmark_test.py -i 230.jpg >> log.txt
python ./poseLandmark_test.py -i 231.jpg >> log.txt
python ./poseLandmark_test.py -i 232.jpg >> log.txt
python ./poseLandmark_test.py -i 233.jpg >> log.txt
python ./poseLandmark_test.py -i 234.jpg >> log.txt
python ./poseLandmark_test.py -i 235.jpg >> log.txt
python ./poseLandmark_test.py -i 236.jpg >> log.txt
python ./poseLandmark_test.py -i 237.jpg >> log.txt
python ./poseLandmark_test.py -i 238.jpg >> log.txt
python ./poseLandmark_test.py -i 239.jpg >> log.txt
python ./poseLandmark_test.py -i 240.jpg >> log.txt
python ./poseLandmark_test.py -i 241.jpg >> log.txt
python ./poseLandmark_test.py -i 242.jpg >> log.txt
python ./poseLandmark_test.py -i 243.jpg >> log.txt
python ./poseLandmark_test.py -i 244.jpg >> log.txt
python ./poseLandmark_test.py -i 245.jpg >> log.txt
python ./poseLandmark_test.py -i 246.jpg >> log.txt
python ./poseLandmark_test.py -i 247.jpg >> log.txt
python ./poseLandmark_test.py -i 248.jpg >> log.txt
python ./poseLandmark_test.py -i 249.jpg >> log.txt
python ./poseLandmark_test.py -i 250.jpg >> log.txt
python ./poseLandmark_test.py -i 251.jpg >> log.txt
python ./poseLandmark_test.py -i 252.jpg >> log.txt
python ./poseLandmark_test.py -i 253.jpg >> log.txt
python ./poseLandmark_test.py -i 254.jpg >> log.txt
python ./poseLandmark_test.py -i 255.jpg >> log.txt
python ./poseLandmark_test.py -i 256.jpg >> log.txt
python ./poseLandmark_test.py -i 257.jpg >> log.txt
python ./poseLandmark_test.py -i 258.jpg >> log.txt
python ./poseLandmark_test.py -i 259.jpg >> log.txt
python ./poseLandmark_test.py -i 260.jpg >> log.txt
python ./poseLandmark_test.py -i 261.jpg >> log.txt
python ./poseLandmark_test.py -i 262.jpg >> log.txt
python ./poseLandmark_test.py -i 263.jpg >> log.txt
python ./poseLandmark_test.py -i 264.jpg >> log.txt
python ./poseLandmark_test.py -i 265.jpg >> log.txt
python ./poseLandmark_test.py -i 266.jpg >> log.txt
python ./poseLandmark_test.py -i 267.jpg >> log.txt
python ./poseLandmark_test.py -i 268.jpg >> log.txt
python ./poseLandmark_test.py -i 269.jpg >> log.txt
python ./poseLandmark_test.py -i 270.jpg >> log.txt
python ./poseLandmark_test.py -i 271.jpg >> log.txt
python ./poseLandmark_test.py -i 272.jpg >> log.txt
python ./poseLandmark_test.py -i 273.jpg >> log.txt
python ./poseLandmark_test.py -i 274.jpg >> log.txt
python ./poseLandmark_test.py -i 275.jpg >> log.txt
python ./poseLandmark_test.py -i 276.jpg >> log.txt
python ./poseLandmark_test.py -i 277.jpg >> log.txt
python ./poseLandmark_test.py -i 278.jpg >> log.txt
python ./poseLandmark_test.py -i 279.jpg >> log.txt
python ./poseLandmark_test.py -i 280.jpg >> log.txt
python ./poseLandmark_test.py -i 281.jpg >> log.txt
python ./poseLandmark_test.py -i 282.jpg >> log.txt
python ./poseLandmark_test.py -i 283.jpg >> log.txt
python ./poseLandmark_test.py -i 284.jpg >> log.txt
python ./poseLandmark_test.py -i 285.jpg >> log.txt
python ./poseLandmark_test.py -i 286.jpg >> log.txt
python ./poseLandmark_test.py -i 287.jpg >> log.txt
python ./poseLandmark_test.py -i 288.jpg >> log.txt
python ./poseLandmark_test.py -i 289.jpg >> log.txt
python ./poseLandmark_test.py -i 290.jpg >> log.txt
python ./poseLandmark_test.py -i 291.jpg >> log.txt
python ./poseLandmark_test.py -i 292.jpg >> log.txt
python ./poseLandmark_test.py -i 293.jpg >> log.txt
python ./poseLandmark_test.py -i 294.jpg >> log.txt
python ./poseLandmark_test.py -i 295.jpg >> log.txt
python ./poseLandmark_test.py -i 296.jpg >> log.txt
python ./poseLandmark_test.py -i 297.jpg >> log.txt
python ./poseLandmark_test.py -i 298.jpg >> log.txt
python ./poseLandmark_test.py -i 299.jpg >> log.txt
python ./poseLandmark_test.py -i 300.jpg >> log.txt
python ./poseLandmark_test.py -i 301.jpg >> log.txt
python ./poseLandmark_test.py -i 302.jpg >> log.txt
python ./poseLandmark_test.py -i 303.jpg >> log.txt
python ./poseLandmark_test.py -i 304.jpg >> log.txt
python ./poseLandmark_test.py -i 305.jpg >> log.txt
python ./poseLandmark_test.py -i 306.jpg >> log.txt
python ./poseLandmark_test.py -i 307.jpg >> log.txt
python ./poseLandmark_test.py -i 308.jpg >> log.txt
python ./poseLandmark_test.py -i 309.jpg >> log.txt
python ./poseLandmark_test.py -i 310.jpg >> log.txt
python ./poseLandmark_test.py -i 311.jpg >> log.txt
python ./poseLandmark_test.py -i 312.jpg >> log.txt
python ./poseLandmark_test.py -i 313.jpg >> log.txt
python ./poseLandmark_test.py -i 314.jpg >> log.txt
python ./poseLandmark_test.py -i 315.jpg >> log.txt
python ./poseLandmark_test.py -i 316.jpg >> log.txt
python ./poseLandmark_test.py -i 317.jpg >> log.txt
python ./poseLandmark_test.py -i 318.jpg >> log.txt
python ./poseLandmark_test.py -i 319.jpg >> log.txt
python ./poseLandmark_test.py -i 320.jpg >> log.txt
python ./poseLandmark_test.py -i 321.jpg >> log.txt
python ./poseLandmark_test.py -i 322.jpg >> log.txt
python ./poseLandmark_test.py -i 323.jpg >> log.txt
python ./poseLandmark_test.py -i 324.jpg >> log.txt
python ./poseLandmark_test.py -i 325.jpg >> log.txt
python ./poseLandmark_test.py -i 326.jpg >> log.txt
python ./poseLandmark_test.py -i 327.jpg >> log.txt
python ./poseLandmark_test.py -i 328.jpg >> log.txt
python ./poseLandmark_test.py -i 329.jpg >> log.txt
python ./poseLandmark_test.py -i 330.jpg >> log.txt
python ./poseLandmark_test.py -i 331.jpg >> log.txt
python ./poseLandmark_test.py -i 332.jpg >> log.txt
python ./poseLandmark_test.py -i 333.jpg >> log.txt
python ./poseLandmark_test.py -i 334.jpg >> log.txt
python ./poseLandmark_test.py -i 335.jpg >> log.txt
python ./poseLandmark_test.py -i 336.jpg >> log.txt
python ./poseLandmark_test.py -i 337.jpg >> log.txt
python ./poseLandmark_test.py -i 338.jpg >> log.txt
python ./poseLandmark_test.py -i 339.jpg >> log.txt
python ./poseLandmark_test.py -i 340.jpg >> log.txt
python ./poseLandmark_test.py -i 341.jpg >> log.txt
python ./poseLandmark_test.py -i 342.jpg >> log.txt
python ./poseLandmark_test.py -i 343.jpg >> log.txt
python ./poseLandmark_test.py -i 344.jpg >> log.txt
python ./poseLandmark_test.py -i 345.jpg >> log.txt
python ./poseLandmark_test.py -i 346.jpg >> log.txt
python ./poseLandmark_test.py -i 347.jpg >> log.txt
python ./poseLandmark_test.py -i 348.jpg >> log.txt
python ./poseLandmark_test.py -i 349.jpg >> log.txt
python ./poseLandmark_test.py -i 350.jpg >> log.txt
python ./poseLandmark_test.py -i 351.jpg >> log.txt
python ./poseLandmark_test.py -i 352.jpg >> log.txt
python ./poseLandmark_test.py -i 353.jpg >> log.txt
python ./poseLandmark_test.py -i 354.jpg >> log.txt
python ./poseLandmark_test.py -i 355.jpg >> log.txt
python ./poseLandmark_test.py -i 356.jpg >> log.txt
python ./poseLandmark_test.py -i 357.jpg >> log.txt
python ./poseLandmark_test.py -i 358.jpg >> log.txt
python ./poseLandmark_test.py -i 359.jpg >> log.txt
python ./poseLandmark_test.py -i 360.jpg >> log.txt
python ./poseLandmark_test.py -i 361.jpg >> log.txt
python ./poseLandmark_test.py -i 362.jpg >> log.txt
python ./poseLandmark_test.py -i 363.jpg >> log.txt
python ./poseLandmark_test.py -i 364.jpg >> log.txt
python ./poseLandmark_test.py -i 365.jpg >> log.txt
python ./poseLandmark_test.py -i 366.jpg >> log.txt
python ./poseLandmark_test.py -i 367.jpg >> log.txt
python ./poseLandmark_test.py -i 368.jpg >> log.txt
python ./poseLandmark_test.py -i 369.jpg >> log.txt
python ./poseLandmark_test.py -i 370.jpg >> log.txt
python ./poseLandmark_test.py -i 371.jpg >> log.txt
python ./poseLandmark_test.py -i 372.jpg >> log.txt
python ./poseLandmark_test.py -i 373.jpg >> log.txt
python ./poseLandmark_test.py -i 374.jpg >> log.txt
python ./poseLandmark_test.py -i 375.jpg >> log.txt
python ./poseLandmark_test.py -i 376.jpg >> log.txt
python ./poseLandmark_test.py -i 377.jpg >> log.txt
python ./poseLandmark_test.py -i 378.jpg >> log.txt
python ./poseLandmark_test.py -i 379.jpg >> log.txt
python ./poseLandmark_test.py -i 380.jpg >> log.txt
python ./poseLandmark_test.py -i 381.jpg >> log.txt
python ./poseLandmark_test.py -i 382.jpg >> log.txt
python ./poseLandmark_test.py -i 383.jpg >> log.txt
python ./poseLandmark_test.py -i 384.jpg >> log.txt
python ./poseLandmark_test.py -i 385.jpg >> log.txt
python ./poseLandmark_test.py -i 386.jpg >> log.txt
python ./poseLandmark_test.py -i 387.jpg >> log.txt
python ./poseLandmark_test.py -i 388.jpg >> log.txt
